nome = "Fernando"
idade = 17
altura = 1.81
tem_carteira = True

print("nome:", nome)
print("idade:", idade)
print("altura:", altura)
print("tem carteira?", tem_carteira)




nome = "tigre"
sobrenome = "siberiano"
idade = 3
quantas_kils = 516
peso = 270,50
altura = 2.10
selvagem = True
fala = False

print("nome:", nome)
print("sobrenome:", sobrenome)
print("idade:", idade)
print("quastas_kils:", quantas_kils)
print("peso:", peso)
print("altura:", altura)
print("selvagem?", selvagem)
print("fala?:", fala)

